training: !!bool "false"
device: "mps"
unprocessed_data: './data/voxceleb/*/*.wav'
---
data:
    train_path: './data/train_tisv'
    train_path_unprocessed: './split_data/train/*/*.wav'
    val_path: './data/val_tisv'
    val_path_unprocessed: './split_data/val/*/*.wav'
    test_path: './data/test_tisv'
    test_path_unprocessed: './split_data/test/*/*.wav'
    data_preprocessed: !!bool "false" 
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 40 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 #Number of LSTM hidden layer units
    num_layer: 3 #Number of LSTM layers
    proj: 256 #Embedding size
    model_path: './speech_id_checkpoint/ckpt_epoch_360_batch_id_28.pth' #Model path for testing, inference, or resuming training
---
train:
    N : 4 #Number of speakers in batch
    M : 7 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.01 
    epochs: 950 #Max training speaker epoch 
    log_interval: 28 #Epochs before printing progress
    log_file: './speech_id_checkpoint/Stats'
    checkpoint_interval: 60 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
val:
    N : 4 #Number of speakers in batch
    M : 4 #Number of utterances per speaker
    num_workers: 0 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
---
test:
    N : 4 #Number of speakers in batch
    M : 4 #Number of utterances per speaker
    num_workers: 0 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
    log_file: './speech_id_checkpoint/Results'

